### ISSUE TITLE
/data

### ISSUE THREAD

**Issue by jnmaloof** [johnny3420/AWS_Setup#1]
Can you add a section on how to create the /data/ folder and a download link for the data?  That way if someone want to set this up on their own computer they can.  Thanks.

**Comment by johnny3420** [comment]
Can do, the filtering process is a little hacky though. I'll put the links
to the original data and the folder creation process

**Comment by jnmaloof** [comment]
Maybe just link (or in addition link) to the filtered data.  Can host on
symposium (/mnt/data/www/downloads/BIS180L)  or on BIS180L Website
(/data/).  The later option is preferred if the files are not too big


Julin Maloof
Professor
Department of Plant Biology
1 Shields Ave
University of California, Davis
Davis, CA 95616
(530) 752 8077
